name: Build and Test

on:
  pull_request:
    branches:
      - 'master'

jobs: 
  build-and-test:
    name: build-and-test
    env:
      PAYSTACK_TEST_PUBLIC_KEY: ${{ secrets.PAYSTACK_TEST_PUBLIC_KEY }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Install dependencies 
      run: flutter pub get
    - name: Check format
      run: dart format . --set-exit-if-changed
    - name: Analyze Dart code
      run: flutter analyze -v
    - name: Run tests
      run: flutter test --coverage
    - name: Coveralls
      uses: coverallsapp/github-action@master

